In [19]:
import numpy as np
a1=np.array([5,6,7])
print("array a1 is: ",a1)
print("Dimension of array is n=", a1.ndim) #n dimension of array
print("Number of elements in array is ",a1.size)
print("Size of each element in the array",a1.itemsize) #int occupies four bytes
print("data type in teh array is :",a1.dtype)

array a1 is:  [5 6 7]
Dimension of array is n= 1
Number of elements in array is  3
Size of each element in the array 4
data type in teh array is : int32


In [23]:
a2=np.array([[1,2],[3,4],[5,6]],dtype=np.float64)
#a2=np.array([[1,2],[3,4],[5,6]],dtype=np.int32)
#a2=np.array([[1,2],[3,4],[5,6]],dtype=complex)
print("array a2 is: ",a2)
print("Dimension of array is n=", a2.ndim) #n dimension of array
print("Number of elements in array is ",a2.size)
print("Size of each element in the array",a2.itemsize) #int occupies four bytes
print("rows and colums of array:", a2.shape)
print("Number of rows in array is :",)
print("Number of columns in array is :",)

array a2 is:  [[1. 2.]
 [3. 4.]
 [5. 6.]]
Dimension of array is n= 2
Number of elements in array is  6
Size of each element in the array 8
rows and colums of array: (3, 2)


In [24]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((5,7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [26]:
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [31]:
#np.linspace(start,stop,number of elements,endpoint=True)
np.linspace(1,20,40,True)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [30]:
np.linspace(1,20,40,False)

array([ 1.   ,  1.475,  1.95 ,  2.425,  2.9  ,  3.375,  3.85 ,  4.325,
        4.8  ,  5.275,  5.75 ,  6.225,  6.7  ,  7.175,  7.65 ,  8.125,
        8.6  ,  9.075,  9.55 , 10.025, 10.5  , 10.975, 11.45 , 11.925,
       12.4  , 12.875, 13.35 , 13.825, 14.3  , 14.775, 15.25 , 15.725,
       16.2  , 16.675, 17.15 , 17.625, 18.1  , 18.575, 19.05 , 19.525])

In [37]:
a3=a2.reshape(2,3)
print(a2,end="\n\n")
print(a3)

[[1. 2.]
 [3. 4.]
 [5. 6.]]

[[1. 2. 3.]
 [4. 5. 6.]]


In [40]:
a3.ravel() # to flatten an array, RETURNS AND DOESNT AFFECT ORIGINAL

array([1., 2., 3., 4., 5., 6.])

In [42]:
print("Array is: \n",a3,end="\n\n")
print("Minimum number in the array is: ", a3.min())
print("Maximum nummber in the array is: ", a3.max())
print("Sum of the elements in the array is: ", a3.sum())
print("Sum of the rows in the array is",a3.sum(axis=1))
print("Sum of the columns in the array is",a3.sum(axis=0))

Array is: 
 [[1. 2. 3.]
 [4. 5. 6.]]

Minimum number in the array is:  1.0
Maximum nummber in the array is:  6.0
Sum of the elements in the array is:  21.0
Sum of the rows in the array is [ 6. 15.]
Sum of the columns in the array is [5. 7. 9.]


In [49]:
#operations
a4=np.array([[1,2],[4,9]])
a5=np.array([[2,4],[8,18]])
print("Sqare root of array:\n",np.sqrt(a4),end="\n\n")
print("standard deviations:", np.std(a3)) #standard deviations

Sqare root of array:
 [[1.         1.41421356]
 [2.         3.        ]]

standard deviations: 1.707825127659933


In [52]:
print("array a4=\n",a4,end="\n\n")
print("array a5=\n",a5,end="\n\n")

print("sum of array:\n",a5+a4)
print("difference of array:\n",a5-a4)
print("multiplication of of array:\n",a5*a4)
print("division of of array:\n",a5/a4)
print("matrix multiplication a5*a4:\n",a5.dot(a4))

array a4=
 [[1 2]
 [4 9]]

array a5=
 [[ 2  4]
 [ 8 18]]

sum of array:
 [[ 3  6]
 [12 27]]
difference of array:
 [[1 2]
 [4 9]]
multiplication of of array:
 [[  2   8]
 [ 32 162]]
division of of array:
 [[2. 2.]
 [2. 2.]]
matrix multiplication a5*a4:
 [[ 18  40]
 [ 80 178]]


Indexing and slicing is simillar to list

In [4]:
ar1 = np.array([4,5,7,6,8,9,7,5,43,5,6,75])
print(ar1[-1])
print(ar1[2:7])

<IPython.core.display.Javascript object>

75
[7 6 8 9 7]


In [12]:
ar2=ar1.reshape(3,4)
print(ar2)
print(ar2[1,2]) #1st row and 2nd column --- count start from 0 to n

print(ar2[-1]) #to print last row

print(ar2[:,2]) #to print a column elements

print(ar2[1]) #to print a row elements


[[ 4  5  7  6]
 [ 8  9  7  5]
 [43  5  6 75]]
7
[43  5  6 75]
[7 7 6]
[8 9 7 5]


In [13]:
#iterations
for row in ar2:
    print(row)

[4 5 7 6]
[8 9 7 5]
[43  5  6 75]


In [16]:
#iterations
for cell in ar2.flat:
    print(cell)

4
5
7
6
8
9
7
5
43
5
6
75


In [18]:
#creating arrays
a=np.arange(6).reshape(3,2)
b=np.arange(7,13). reshape(3,2)
print(a)
print(b)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

[[0 1]
 [2 3]
 [4 5]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [21]:
np.vstack((a,b)) #for vertical stacking of two matrices (one over the other)

<IPython.core.display.Javascript object>

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [22]:
np.hstack((a,b)) #for vertical stacking of two matrices (side by side)

<IPython.core.display.Javascript object>

array([[ 0,  1,  7,  8],
       [ 2,  3,  9, 10],
       [ 4,  5, 11, 12]])

In [27]:
a=np.arange(30).reshape(2,15)
print(a)
print(np.hsplit(a,3))
print(np.vsplit(a,2))

<IPython.core.display.Javascript object>

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


<IPython.core.display.Javascript object>

[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]


<IPython.core.display.Javascript object>

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]


In [37]:
a=a.reshape(6,5)
print(a)
b=a%5==0
c=a>15
print(b)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ True False False False False]
 [ True False False False False]
 [ True False False False False]
 [ True False False False False]
 [ True False False False False]
 [ True False False False False]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [40]:
print(a[b]) #display array 'a' content whenever corresponding content in b is True
print(a[c]) #this is simple method to extract all elements in an array where a condtion is satified

[ 0  5 10 15 20 25]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [42]:
a[b]=-1  #we can assign a fixed value to elements of an array when a condition is satisfied
print(a)

[[-1  1  2  3  4]
 [-1  6  7  8  9]
 [-1 11 12 13 14]
 [-1 16 17 18 19]
 [-1 21 22 23 24]
 [-1 26 27 28 29]]


In [48]:
a=np.arange(12).reshape(3,4)
print(a)

<IPython.core.display.Javascript object>

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# nditer function

In [51]:
for x in np.nditer(a,order='C'):  #displays in horizontal (C) order (just we read book in row wise)
    print(x)

<IPython.core.display.Javascript object>

0
1
2
3
4
5
6
7
8
9
10
11


In [52]:
for x in np.nditer(a,order='F'):  #displays in vertical (Fortran) order (just we write numbers verticay)
    print(x)

<IPython.core.display.Javascript object>

0
4
8
1
5
9
2
6
10
3
7
11


use nditer document in website for more details

In [53]:
for x in np.nditer(a,order='F',flags=['external_loop']):  #displays in vertical (Fortran) order (just we write numbers verticay)
    print(x)

<IPython.core.display.Javascript object>

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [62]:
a=np.arange(12).reshape(3,4)   #to perform operation on array and to store in the same location
print(a)
for x in np.nditer(a,op_flags=['readwrite']):  #displays in vertical (Fortran) order (just we write numbers verticay)
    x[...]=x*x
print(a)

<IPython.core.display.Javascript object>

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


<IPython.core.display.Javascript object>

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [64]:
b=np.arange(12).reshape(3,4)   #the shape shoud be same or one of the array should have dimension 1
for x,y in np.nditer([b,a]):
    print("Square of ",x,"is",y)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Square of  0 is 0
Square of  1 is 1
Square of  2 is 4
Square of  3 is 9
Square of  4 is 16
Square of  5 is 25
Square of  6 is 36
Square of  7 is 49
Square of  8 is 64
Square of  9 is 81
Square of  10 is 100
Square of  11 is 121


Key benifits of np.array:
    Less memory
    Faster
    Convinent
        compared to list

In [69]:
l=range(1000)
n=np.arange(1000)

print(sys.getsizeof(5)*len(l))   #5 is a dummy object
print(n.size*n.itemsize)


#in list every element is an object and hence alloted 28 bytes in this case
#where as array occupies 4 bytes for integer
#hence np.arrays occupies less space compared to list

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

28000
4000


In [71]:
import numpy as np
import time
import sys

SIZE=1000000

l1=range(SIZE)
l2=range(SIZE)

a1=np.arange(SIZE)
a2=np.arange(SIZE)

start = time.time()
result =[(x+y) for x,y in zip(l1,l2)]
print("python list took: ",(time.time()-start)*1000,"msec")
      
start = time.time()
a=a1+a2
print("numpy array took: ",(time.time()-start)*1000,"msec")
      

python list took:  373.02112579345703 msec
numpy array took:  4.000425338745117 msec
